// ===== GLOBAL STATE =====
const AppState = {
  currentToken: null,
  currentUserId: null,
  currentUsername: null,
  selectedProject: null,
  projectsList: [],
  autoGeneratedWorklogs: [],
};

// ===== MAIN ORCHESTRATION =====

// Initialize when DOM is loaded
document.addEventListener("DOMContentLoaded", function () {
  // Attach event listener to start button
  const startButton = document.getElementById("startButton");
  if (startButton) {
    startButton.addEventListener("click", showWorklogTool);
  }

  // Use event delegation for dynamically created buttons
  document.body.addEventListener("click", function (e) {
    const target = e.target;

    // Handle different button clicks
    if (target.id === "continueTokenBtn") {
      continueWithToken();
    } else if (target.id === "manualInputBtn") {
      showManualInputFlow();
    } else if (target.id === "autoBtn") {
      startAutoFlow();
    } else if (target.id === "loadProjectsBtn") {
      loadProjectsWithDateRange();
    } else if (target.id === "submitBtn") {
      submitWorklog();
    } else if (target.classList.contains("changeDatesBtn")) {
      showDateRangeSelector().catch(console.error);
    } else if (target.classList.contains("updateTokenBtn")) {
      showTokenInput().catch(console.error);
    } else if (target.classList.contains("retryLoadBtn")) {
      loadProjectsWithDateRange();
    }
  });

  // Handle select and input changes
  document.body.addEventListener("change", function (e) {
    const target = e.target;

    if (target.id === "projectSelect") {
      onProjectSelected();
    } else if (target.id === "workHours") {
      updateWorklogPreview();
    }
  });
});

async function showWorklogTool() {
  const container = document.querySelector(".container");
  const worklogContainer = document.getElementById("worklogContainer");
  const initialContent = document.getElementById("initialContent");

  // Remove initial content from DOM to prevent showing through backdrop-filter
  if (initialContent) {
    initialContent.remove();
  }

  // Show worklog container and ensure it covers the entire container
  worklogContainer.style.display = "block";

  // Try to extract token automatically first
  AppState.currentToken = await findAccessToken();

  // Show token input form
  await showTokenInput();
}

async function showManualInputFlow() {
  // Fetch user ID if not already fetched
  if (!AppState.currentUserId) {
    try {
      await fetchCurrentUserId();
    } catch (error) {
      await showTokenInput();
      return;
    }
  }
  // Show date range selector (existing manual flow)
  await showDateRangeSelector();
}

async function startAutoFlow() {
  const worklogContainer = document.getElementById("worklogContainer");

  // Fetch user ID if not already fetched
  if (!AppState.currentUserId) {
    try {
      await fetchCurrentUserId();
    } catch (error) {
      alert(`Error fetching user information: ${error.message}`);
      await showModeSelection();
      return;
    }
  }

  // Calculate date range: start of current month to today
  const startOfMonth = getStartOfMonth();
  const today = new Date();

  const startDateStr = formatDate(startOfMonth);
  const endDateStr = formatDate(today);

  // Store the selected dates
  window.selectedStartDate = startDateStr;
  window.selectedEndDate = endDateStr;

  // Show loading
  const html = await loadTemplate("loading-projects", {
    START_DATE: startDateStr,
    END_DATE: endDateStr,
  });
  worklogContainer.innerHTML = html;

  // Load projects with auto date range
  await loadProjectsForAutoFlow();
}

async function continueWithToken() {
  let tokenInput = document.getElementById("tokenInput").value;

  // Clean up the token: remove extra spaces, newlines, and "Bearer" prefix
  tokenInput = tokenInput.trim().replace(/\s+/g, " "); // Replace multiple spaces/newlines with single space
  tokenInput = tokenInput.replace(/\n/g, ""); // Remove any newlines

  // Remove "Bearer " prefix if present (case insensitive)
  if (tokenInput.toLowerCase().startsWith("bearer ")) {
    tokenInput = tokenInput.substring(7).trim();
  }

  if (!tokenInput) {
    alert("Please paste your access token first!");
    return;
  }

  AppState.currentToken = tokenInput;

  // Save token to chrome storage for persistence
  await chrome.storage.local.set({ smo_token: AppState.currentToken });

  // Fetch user ID from the token
  try {
    await fetchCurrentUserId();
  } catch (error) {
    await showTokenInput();
    return;
  }

  // Show date range selector first
  await showDateRangeSelector();
}

async function loadProjectsWithDateRange() {
  const startDateInput = document.getElementById("startDateInitial").value;
  const endDateInput = document.getElementById("endDateInitial").value;

  if (!startDateInput || !endDateInput) {
    alert("Please select both start and end dates!");
    return;
  }

  const startDate = new Date(startDateInput);
  const endDate = new Date(endDateInput);

  if (startDate > endDate) {
    alert("Start date must be before or equal to end date!");
    return;
  }

  const worklogContainer = document.getElementById("worklogContainer");
  const html = await loadTemplate("loading-projects", {
    START_DATE: startDateInput,
    END_DATE: endDateInput,
  });
  worklogContainer.innerHTML = html;

  // Store the selected dates for later use
  window.selectedStartDate = startDateInput;
  window.selectedEndDate = endDateInput;

  // Fetch projects using the selected date
  await loadProjects();
}
