// ===== GLOBAL STATE =====
const AppState = {
  currentToken: null,
  currentUserId: null,
  currentUsername: null,
  selectedProject: null,
  projectsList: [],
  autoGeneratedWorklogs: [],
};

// ===== MAIN ORCHESTRATION =====

// Initialize when DOM is loaded
document.addEventListener("DOMContentLoaded", function () {
  // Attach event listener to start button
  const startButton = document.getElementById("startButton");
  if (startButton) {
    startButton.addEventListener("click", showWorklogTool);
  }

  // Attach event listener to start add resource button
  const startAddResourceButton = document.getElementById("startAddResourceButton");
  if (startAddResourceButton) {
    startAddResourceButton.addEventListener("click", showAddResourceTool);
  }

  // Use event delegation for dynamically created buttons
  document.body.addEventListener("click", function (e) {
    const target = e.target;

    // Handle different button clicks
    if (target.id === "continueTokenBtn") {
      continueWithToken();
    } else if (target.id === "openSraBtn") {
      window.open("https://sra.smartosc.com", "_blank");
    } else if (target.id === "manualInputBtn") {
      showManualInputFlow();
    } else if (target.id === "autoBtn") {
      startAutoFlow();
    } else if (target.id === "loadProjectsBtn") {
      loadProjectsWithDateRange();
    } else if (target.id === "submitBtn") {
      submitWorklog();
    } else if (target.classList.contains("changeDatesBtn")) {
      showDateRangeSelector().catch(console.error);
    } else if (target.classList.contains("updateTokenBtn")) {
      showTokenInput().catch(console.error);
    } else if (target.classList.contains("retryLoadBtn")) {
      loadProjectsWithDateRange();
    } else if (target.id === "logoutBtn") {
      logout();
    }
  });

  // Handle select and input changes
  document.body.addEventListener("change", function (e) {
    const target = e.target;

    if (target.id === "projectSelect") {
      onProjectSelected();
    } else if (target.id === "workHours") {
      updateWorklogPreview();
    }
  });

  // Run the permission check behind a loading screen, then reveal the
  // initial content with the correct buttons already in place - avoids
  // the "Add Resource" button flashing on screen then disappearing.
  initializeApp();
});

// Clears the captured token/user data and sends the popup back to the
// initial screen, so the user can log in again (e.g. with a different
// account).
async function logout() {
  const confirmed = confirm("Log out and clear your saved access token?");
  if (!confirmed) {
    return;
  }

  await chrome.storage.local.remove([
    "smo_token",
    "token_captured_at",
    "smo_userId",
    "smo_username",
    "smo_userName",
    "smo_userEmail",
  ]);

  location.reload();
}

async function initializeApp() {
  const loadingScreen = document.getElementById("appLoadingScreen");
  const initialContent = document.getElementById("initialContent");
  const startAddResourceButton = document.getElementById("startAddResourceButton");

  // Keep the loading screen visible for at least this long, even if the
  // checks resolve instantly, so it reads as a deliberate loading step
  // instead of a quick flash.
  const MIN_LOADING_TIME_MS = 600;
  const minLoadingTimer = new Promise((resolve) => setTimeout(resolve, MIN_LOADING_TIME_MS));

  // Whether we should skip the "Logging Work / Add Resource" screen entirely
  // and go straight to the "Open SRA" login screen instead.
  let needsLogin = false;

  try {
    const token = await findAccessToken();

    if (!token) {
      needsLogin = true;
    } else {
      AppState.currentToken = token;

      const tokenValid = await isTokenValid();

      if (tokenValid === false) {
        // Token is expired/invalid - clear it and force the login screen
        // instead of showing the main screen with a token that will fail.
        needsLogin = true;
        AppState.currentToken = null;
        AppState.currentUserId = null;
        AppState.currentUsername = null;
        await chrome.storage.local.remove([
          "smo_token",
          "token_captured_at",
          "smo_userId",
          "smo_username",
          "smo_userName",
          "smo_userEmail",
        ]);
      } else {
        // Valid, or inconclusive (e.g. network error) - proceed as normal.
        const hasPermission = await checkViewProjectListPermission();
        if (hasPermission === false && startAddResourceButton) {
          startAddResourceButton.style.display = "none";
        }
      }
    }
  } catch (error) {
    // Inconclusive - fall back to showing the normal screen
  } finally {
    await minLoadingTimer;
    if (loadingScreen) {
      loadingScreen.style.display = "none";
    }

    if (needsLogin) {
      await showLoginRequiredScreen();
    } else if (initialContent) {
      initialContent.style.display = "";
    }
  }
}

// Skips the "Logging Work / Add Resource" screen and shows the token/login
// screen (with the "Open SRA" + "Continue with Token" buttons) directly.
// Used when no token is captured yet, or the saved token has expired.
async function showLoginRequiredScreen() {
  const initialContent = document.getElementById("initialContent");
  const worklogContainer = document.getElementById("worklogContainer");

  if (initialContent) {
    initialContent.remove();
  }
  if (worklogContainer) {
    worklogContainer.style.display = "block";
  }

  await showTokenInput();
}

async function showWorklogTool() {
  const container = document.querySelector(".container");
  const worklogContainer = document.getElementById("worklogContainer");
  const initialContent = document.getElementById("initialContent");

  // Remove initial content from DOM to prevent showing through backdrop-filter
  if (initialContent) {
    initialContent.remove();
  }

  // Show worklog container and ensure it covers the entire container
  worklogContainer.style.display = "block";

  // Try to extract token automatically first
  AppState.currentToken = await findAccessToken();

  // Show token input form
  await showTokenInput();
}

async function showManualInputFlow() {
  // Fetch user ID if not already fetched
  if (!AppState.currentUserId) {
    try {
      await fetchCurrentUserId();
    } catch (error) {
      await showTokenInput();
      return;
    }
  }
  // Show date range selector (existing manual flow)
  await showDateRangeSelector();
}

async function startAutoFlow() {
  const worklogContainer = document.getElementById("worklogContainer");

  // Fetch user ID if not already fetched
  if (!AppState.currentUserId) {
    try {
      await fetchCurrentUserId();
    } catch (error) {
      alert(`Error fetching user information: ${error.message}`);
      await showModeSelection();
      return;
    }
  }

  // Calculate date range: start of current month to today
  const startOfMonth = getStartOfMonth();
  const today = new Date();

  const startDateStr = formatDate(startOfMonth);
  const endDateStr = formatDate(today);

  // Store the selected dates
  window.selectedStartDate = startDateStr;
  window.selectedEndDate = endDateStr;

  // Show loading
  const html = await loadTemplate("loading-projects", {
    START_DATE: startDateStr,
    END_DATE: endDateStr,
  });
  worklogContainer.innerHTML = html;

  // Load projects with auto date range
  await loadProjectsForAutoFlow();
}

async function continueWithToken() {
  let tokenInput = document.getElementById("tokenInput").value;

  // Clean up the token: remove extra spaces, newlines, and "Bearer" prefix
  tokenInput = tokenInput.trim().replace(/\s+/g, " "); // Replace multiple spaces/newlines with single space
  tokenInput = tokenInput.replace(/\n/g, ""); // Remove any newlines

  // Remove "Bearer " prefix if present (case insensitive)
  if (tokenInput.toLowerCase().startsWith("bearer ")) {
    tokenInput = tokenInput.substring(7).trim();
  }

  if (!tokenInput) {
    alert("Please paste your access token first!");
    return;
  }

  AppState.currentToken = tokenInput;

  // Save token to chrome storage for persistence
  await chrome.storage.local.set({ smo_token: AppState.currentToken });

  // Fetch user ID from the token
  try {
    await fetchCurrentUserId();
  } catch (error) {
    await showTokenInput();
    return;
  }

  // Show date range selector first
  await showDateRangeSelector();
}

async function loadProjectsWithDateRange() {
  const startDateInput = document.getElementById("startDateInitial").value;
  const endDateInput = document.getElementById("endDateInitial").value;

  if (!startDateInput || !endDateInput) {
    alert("Please select both start and end dates!");
    return;
  }

  const startDate = new Date(startDateInput);
  const endDate = new Date(endDateInput);

  if (startDate > endDate) {
    alert("Start date must be before or equal to end date!");
    return;
  }

  const worklogContainer = document.getElementById("worklogContainer");
  const html = await loadTemplate("loading-projects", {
    START_DATE: startDateInput,
    END_DATE: endDateInput,
  });
  worklogContainer.innerHTML = html;

  // Store the selected dates for later use
  window.selectedStartDate = startDateInput;
  window.selectedEndDate = endDateInput;

  // Fetch projects using the selected date
  await loadProjects();
}

// ===== ADD RESOURCE FLOW =====

async function showAddResourceTool() {
  const container = document.querySelector(".container");
  const worklogContainer = document.getElementById("worklogContainer");
  const initialContent = document.getElementById("initialContent");

  // Remove initial content from DOM
  if (initialContent) {
    initialContent.remove();
  }

  // Show worklog container
  worklogContainer.style.display = "block";

  // Try to extract token automatically first
  AppState.currentToken = await findAccessToken();

  // Check if token exists
  if (!AppState.currentToken) {
    worklogContainer.innerHTML = `
      <div style="padding: 20px; text-align: center;">
        <p style="color: rgba(255, 255, 255, 0.9); text-shadow: 0 1px 3px rgba(0, 0, 0, 0.15); margin-bottom: 15px;">
          Please login to SRA SmartOSC first to capture your access token.
        </p>
        <button class="info" onclick="location.reload()" style="margin-top: 15px;">Go Back</button>
      </div>
    `;
    return;
  }

  // Show loading message
  worklogContainer.innerHTML = `
    <div style="padding: 20px; text-align: center;">
      <p style="color: rgba(255, 255, 255, 0.9); text-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);">
        Loading projects...
      </p>
    </div>
  `;

  // Fetch and display projects list
  try {
    // Check if required functions are available
    if (typeof fetchProjectsList === 'undefined') {
      throw new Error('fetchProjectsList is not defined. Please check if api/api.js is loaded.');
    }
    if (typeof renderProjectsList === 'undefined') {
      throw new Error('renderProjectsList is not defined. Please check if ui/renderers.js is loaded.');
    }

    const data = await fetchProjectsList(1);
    window.lastProjectsData = data;
    await renderProjectsList(data, 1);
  } catch (error) {
    worklogContainer.innerHTML = `
      <div style="padding: 20px; text-align: center;">
        <p style="color: rgba(255, 255, 255, 0.9); text-shadow: 0 1px 3px rgba(0, 0, 0, 0.15); margin-bottom: 15px;">
          Error loading projects: ${error.message}
        </p>
        <button class="danger" onclick="location.reload()" style="margin-top: 15px;">Go Back</button>
      </div>
    `;
  }
}
